name: Deploy from branch

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: 'Action Type'
        required: true
        options:
          - deploy-app
          - deploy-services
      branch:
        description: 'Source Branch'
        required: true
        options:
          - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_SECRET_KEY: ${{ secrets.APP_SECRET_KEY }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASS: ${{ secrets.DATABASE_PASS }}
      DEPLOY_BRANCH: ${{ inputs.branch || github.base_ref || github.ref_name }}
      DEPLOY_TAG: ${{ inputs.tag || 'deploy-app' }}
    steps:
      - name: Cache Ansible
        id: cache-ansible
        uses: actions/cache@v3
        with:
          path: /etc/ansible
          key: ${{ runner.os }}-ansible

      - name: Install ansible 
        if: steps.cache-ansible.outputs.cache-hit != 'true'
        run: |
          sudo apt install -y software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt install ansible

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        if: ${{ inputs.tag }} != 'deploy-services'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Build and push image
        if: ${{ env.DEPLOY_TAG }} == 'deploy-app'
        uses: docker/build-push-action@v4
        with:
          tags: ${{ secrets.CONTAINER_IMAGE }}:${{ env.DEPLOY_BRANCH }}-latest
          pull: true
          cache-from: ${{ secrets.CONTAINER_IMAGE }}:${{ env.DEPLOY_BRANCH }}-latest
          push: true

      - name: Add SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}

      - name: Run playbook
        run: >
          ansible-playbook 
          -i infra/inventory/chemical-storage 
          -e env=${{ env.DEPLOY_BRANCH }} 
          -l ${{ env.DEPLOY_BRANCH }} 
          -t ${{ env.DEPLOY_TAG }} 
          -v infra/playbook.yml 

